### ISSUE TITLE
[Bug]: fetching spotify stream slow and sometime fails 

### ISSUE THREAD

**Issue by KagChi** [noaione/spotilava#2]
from commit https://github.com/noaione/spotilava/commit/cc21f8d3c35392aba71fba60bca6d696eb511c5f resolve spotify stream a bit slow. than before, and also sometimes there is an error can't find mp3

**Comment by noaione** [comment]
Can you give me the track you're trying to fetch that have noticeable slow down, and also the track that give error for MP3 file.

**Comment by KagChi** [comment]
seems to be fixed, maybe because of a lot of traffic so it's a bit slow
